<a href="https://colab.research.google.com/github/SaraBCoutinho/2020.2-agentes_cognitivos_e_adaptativos/blob/main/LIAR_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Introduçao 

Sites: 

https://huggingface.co/datasets/liar 

https://www.kaggle.com/c/fake-news/data

https://github.com/mansoor9743/Fake-News-Detection/blob/master/code/Fake_news_detection.ipynb

https://github.com/ekagra-ranjan/fake-news-detection-LIAR-pytorch/blob/master/data.py

https://www.kaggle.com/clmentbisaillon/classifying-fake-news-with-bert 

https://www.youtube.com/watch?v=lwZgvzw6YCs

https://stackoverflow.com/questions/50184280/how-to-conceptually-think-about-relationship-between-tokenized-words-and-word-em, 

https://github.com/hmohebbi/SentimentAnalysis/blob/master/main.ipynb USADO 

https://www.quora.com/What-are-the-main-differences-between-the-word-embeddings-of-ELMo-BERT-Word2vec-and-GloVe LER PARA DUVIDAS 

!pip install  https://docs.python.org/3.8/library/itertools.html#module-itertools

No experimento, reproduzir. O dataset nao precisa criar os k folds porque nao faz o cross validation, os conjuntos de treino e teste ja sao definidos e usados na literatura. O tratamento dos dados vai de acordo com a literatura. Foram usados os statement como x e label como y. Além disso, 6 representaçoes (inovando com o bert) e mais 8 classificadores, totalizando 48 resultados. 
Depois feita a binarizaçao e re-reproduçao do experimento. 

Duvidas: o selectorKbest no pipeline p/ tfidf e cv ; comparativo quando nao se tem muita diferença usando a matriz de confusao. Uso de Bernoulli e Multinomial em NB . No diversity analysis nao gerei os folds, ver se as funçoes sao retiradas. Duvida no fine-tuning do Bert. Methods, no diversity analysis, seriam as prediçoes? Na verdade ver o X e y e  a parte de label e methods

Possivel bert: https://medium.com/@vslovik/fake-news-detection-empowered-with-bert-and-friends-20397f7e1675 

### Imports

In [1]:
#--Data
!pip install datasets
from datasets import load_dataset
import pandas as pd
#--Data analysis 
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from wordcloud import STOPWORDS, WordCloud
!pip install ftfy
# import libraries
import ftfy
import nltk
import json
import re
%matplotlib inline
import pandas as pd
import csv
import numpy as np
import nltk
import seaborn as sb
import warnings

from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_validate, StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.preprocessing import Binarizer

from collections import Counter
from os import listdir, makedirs
from os.path import isfile, join, splitext, split

from nltk.stem import SnowballStemmer
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from collections import defaultdict
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

from nltk import pos_tag
#nltk.download('stopwords')

from wordcloud import STOPWORDS, WordCloud

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import cross_validate, StratifiedKFold
from sklearn.naive_bayes import GaussianNB

from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn import model_selection, naive_bayes, svm
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier # need to import xboost calssifer

warnings.filterwarnings('ignore')
np.random.seed(0)

import nltk
nltk.download('stopwords')

# stop words list set to english
stopwords_list = stopwords.words('english') # stop word list

""" Regular expression for cleaning the statements"""
import re

hashtag_re = re.compile(r"#\w+")
mention_re = re.compile(r"@\w+")
url_re = re.compile(r"(?:https?://)?(?:[-\w]+\.)+[a-zA-Z]{2,9}[-\w/#~:;.?+=&%@~]*")
extras_re = re.compile("[.;:!\'?,\"()\[\]]")
#apos_re = "\'[a-z]*"
#leftover_re = "\S+"

from unicodedata import normalize

!pip install zeugma
!pip install preprocessing
!pip install function

from zeugma.embeddings import EmbeddingTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from preprocessing import *
from function import *

#!pip install itertools
import itertools
!pip install mxnet
import mxnet as mx
!pip install bert_embedding
from bert_embedding import BertEmbedding

     |████████████████████████████████| 306 kB 15.1 MB/s 
     |████████████████████████████████| 1.1 MB 56.3 MB/s 
     |████████████████████████████████| 61 kB 476 kB/s 
     |████████████████████████████████| 243 kB 60.9 MB/s 
     |████████████████████████████████| 132 kB 59.6 MB/s 
     |████████████████████████████████| 271 kB 49.9 MB/s 
     |████████████████████████████████| 160 kB 38.2 MB/s 
     |████████████████████████████████| 192 kB 58.3 MB/s 
     |████████████████████████████████| 64 kB 1.9 MB/s 
  Created wheel for ftfy: filename=ftfy-6.0.3-py3-none-any.whl size=41933 sha256=2083e73ec80a39aecbb5df9786b52afe381b3c1fb3a34b2ebfc541de2fe78133
  Stored in directory: /root/.cache/pip/wheels/19/f5/38/273eb3b5e76dfd850619312f693716ac4518b498f5ffb6f56d
Successfully built ftfy
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
  Created wheel for zeugma: filename=zeugma-0.49-py3-none-any.whl size=8821 sha256=bb378955cc5

  Created wheel for function: filename=function-1.2.0-py3-none-any.whl size=1463 sha256=67655cf420f7867b2bca89a184ff100a3850b619538e992fc5309c4321658dea
  Stored in directory: /root/.cache/pip/wheels/97/ac/86/0db3a8b76385994e22ec07808657e3584de609026808a32ca6
Successfully built function
     |████████████████████████████████| 47.3 MB 1.4 MB/s 
  Attempting uninstall: graphviz
    Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1
     |████████████████████████████████| 29.6 MB 1.4 MB/s 
     |████████████████████████████████| 13.8 MB 49.4 MB/s 
     |████████████████████████████████| 209 kB 70.0 MB/s 
  Created wheel for gluonnlp: filename=gluonnlp-0.6.0-py3-none-any.whl size=259930 sha256=b2cd96359cc812311cc9eec60c294c1db64807c143a32a8b6e6a3a2c1457ffbc
  Stored in directory: /root/.cache/pip/wheels/a6/41/8f/45bd1c58055d87aee5a71b6756a427ea8d92e506b3a9d17370
Successfully built gluonnlp
  Attempting uninstall: nu

### Data 

In [2]:
dataset = load_dataset('liar')

Downloading:   0%|          | 0.00/2.33k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.68k [00:00<?, ?B/s]

Using custom data configuration default


Downloading:   0%|          | 0.00/1.01M [00:00<?, ?B/s]

0 examples [00:00, ? examples/s]

0 examples [00:00, ? examples/s]

0 examples [00:00, ? examples/s]

Dataset liar downloaded and prepared to /root/.cache/huggingface/datasets/liar/default/1.0.0/479463e757b7991eed50ffa7504d7788d6218631a484442e2098dabbf3b44514. Subsequent calls will reuse this data.


  0%|          | 0/3 [00:00<?, ?it/s]

#### Pre processing

In [3]:
#data
train=pd.DataFrame(dataset['train'])
test=pd.DataFrame(dataset['test'])
val=pd.DataFrame(dataset['validation'])
print(train.shape,test.shape,val.shape)

(10269, 14) (1283, 14) (1284, 14)


label_to_number_6_way_classification = {'pants-fire': 0,'false': 1,'barely-true': 2,'half-true': 3,'mostly-true': 4,'true': 5}

label_to_number_2_way_classification = {'pants-fire': 0,'false': 0,'barely-true': 0,'half-true': 1,'mostly-true': 1,'true': 1}

In [4]:
Original_labels={5:1, 4:1, 3:1, 1:0,2:0,0:0}
train['label'] = train['label'].map(Original_labels)
test['label'] = test['label'].map(Original_labels)
val['label'] = val['label'].map(Original_labels)

In [5]:
df_raw = pd.concat([train, test, val], axis=0, sort=False)
df_raw = df_raw.sample(frac=1).reset_index()

In [77]:
print(train['label'].unique())
print(test['label'].unique())
print(val['label'].unique())

[0 1]
[1 0]
[1 0]


#### Divisao X e Y 

In [6]:
# specifying features and labels
X= df_raw['statement']
y=df_raw['label']

#### Divisao Treino e teste 

In [7]:
from sklearn.model_selection import train_test_split
# specifying train and test split with ratio of 80:20
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state = 0, stratify=y)
print(len(X_train), len(X_test))
print(len(y_train), len(y_test))

10268 2568
10268 2568


#### Pre processamento 

In [8]:
""" Preprocessing the text in the statements"""
def preprocess(text):
    p_text = hashtag_re.sub("[hashtag]",text)
    p_text = mention_re.sub("[mention]",p_text)
    p_text = extras_re.sub("",p_text)
    p_text = url_re.sub("[url]",p_text) #removing url
    p_text = ftfy.fix_text(p_text)
    return p_text.lower()

# regular expression for custom tokenisation"
tokenise_re = re.compile(r"(\[[^\]]+\]|[-'\w]+|[^\s\w\[']+)") #([]|words|other non-space)

# defining 3 types of tokenisation

def custom_tokenise(text):
    return tokenise_re.findall(text.lower())

def Tokenizer(str_input):
    words = re.sub(r"[^A-Za-z0-9\-]", " ", str_input).lower().split()
    porter_stemmer=nltk.PorterStemmer()
    words = [porter_stemmer.stem(word) for word in words]
    return words


def nltk_twitter_tokenise(text):
    twtok = nltk.tokenize.TweetTokenizer()
    return twtok.tokenize(text.lower())

# stop words list set to english
#stopwords_list = stopwords.words('english') # stop word list

#### Métricas 

In [9]:
# function for results of cross-validation
def print_cv_scores_summary(name, scores):
    print("{}: mean = {:.2f}%, sd = {:.2f}%, min = {:.2f}, max = {:.2f}".format(name, scores.mean()*100, scores.std()*100, scores.min()*100, scores.max()*100))


# fucntion for results of model fitting
def print_scores():
    print("Accuracy: ", accuracy_score(y_test, predictions))
    print(classification_report(y_test, predictions))
    print(confusion_matrix(y_test, predictions))
    
# function for displaying confusion matrix
def confusion_matrix_heatmap(cm, index):
    cmdf = pd.DataFrame(cm, index = index, columns=index)
    dims = (10, 8)
    fig, ax = plt.subplots(figsize=dims)
    sns.heatmap(cmdf, annot=True, cmap="BuPu", center=0, fmt='g')
    ax.set_ylabel('Actual')    
    ax.set_xlabel('Predicted')

# function for displaying confusion matrix in percentage terms
def confusion_matrix_percent_heatmap(cm, index):
    cmdf = pd.DataFrame(cm, index = index, columns=index)
    percents = cmdf.div(cmdf.sum(axis=1), axis=0)*100
    dims = (10, 10)
    fig, ax = plt.subplots(figsize=dims)
    sns.heatmap(percents, annot=True, cmap="PiYG", center=0, vmin=0, vmax=100)
    ax.set_ylabel('Actual')    
    ax.set_xlabel('Predicted')
    cbar = ax.collections[0].colorbar
    cbar.set_ticks([0, 25, 50, 75, 100])
    cbar.set_ticklabels(['0%', '25%', '50%', '75%', '100%'])
    
#list(df_columns.columns))-list(df_raw['labels'])"coolwarm"'Blues'PiYG'BuPu'

#### Modelos 2 classes

###### Embeddings 

Bag of words: TF , TF IDF

Dense Word Embeddings : Glove, Word2Vec, Fast Text 

Proposta : Bert (retirar camadas finais) 

Dense Word Embeddings

In [18]:
w2v = EmbeddingTransformer('word2vec')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [19]:
glove = EmbeddingTransformer('glove')

[==================================================] 100.0% 104.8/104.8MB downloaded


In [20]:
fasttext = EmbeddingTransformer('fasttext')

[==================================================] 100.0% 958.5/958.4MB downloaded


In [21]:
cv = CountVectorizer(analyzer='word', lowercase=True, stop_words='english')

In [22]:
tfidf =  TfidfVectorizer(analyzer='word', lowercase=True, use_idf=True, stop_words='english')

In [10]:
# Cleaning before BERT
embedding = 'BERT'

In [11]:
def mean(z): # used for BERT (word version) and Word2Vec
    return sum(itertools.chain(z))/len(z)

In [12]:
def embeddToBERT(text):
    sentences = re.split('!|\?|\.',text)
    sentences = list(filter(None, sentences)) 

    if bert_version == 'WORD':
        result = bert(sentences, 'avg') # avg is refer to handle OOV
    
        bert_vocabs_of_sentence = []
        for sentence in range(len(result)):
            for word in range(len(result[sentence][1])):
                bert_vocabs_of_sentence.append(result[sentence][1][word])
        feature = [mean(x) for x in zip(*bert_vocabs_of_sentence)]

    elif bert_version == 'SENTENCE':
        result = bert_transformers.encode(sentences)
        feature = [mean(x) for x in zip(*result)]
  
    return feature

In [13]:
bert = BertEmbedding()

Vocab file is not found. Downloading.


In [14]:
bert_version = 'WORD'

In [15]:
bert_word_training_features = X_train.apply(embeddToBERT)

In [16]:
bert_word_test_features = X_test.apply(embeddToBERT)

In [17]:
feature = [x for x in bert_word_training_features.transpose()]
bert_word_training_features = np.asarray(feature)
feature = [x for x in bert_word_test_features.transpose()]
bert_word_test_features = np.asarray(feature)
print(bert_word_training_features.shape)

(10268, 768)


##### SVR 

In [23]:
from sklearn.svm import SVC

###### Tf-idf 

In [24]:
model = Pipeline([('vectorizer', tfidf),('selector', SelectKBest(chi2, k=100)),('clf', SVC(random_state=42, kernel='linear', gamma=0.1, probability=True)),])
model.fit(X_train, y_train)# fitting the model
predictions = model.predict(X_test)
print_scores() # using the predefined function to display results of the classification
#model.set_params(embedding__max_features=1000)# limiting the max features to 1000 and checking the model

Accuracy:  0.5915109034267912
              precision    recall  f1-score   support

           0       0.59      0.98      0.74      1523
           1       0.47      0.03      0.05      1045

    accuracy                           0.59      2568
   macro avg       0.53      0.50      0.40      2568
weighted avg       0.54      0.59      0.46      2568

[[1489   34]
 [1015   30]]


In [25]:
model = Pipeline([('vectorizer', tfidf),('clf', SVC(random_state=42, kernel='linear', gamma=0.1, probability=True)),])
model.fit(X_train, y_train)# fitting the model
predictions = model.predict(X_test)
print_scores() # using the predefined function to display results of the classification
#model.set_params(embedding__max_features=1000)# limiting the max features to 1000 and checking the model

Accuracy:  0.5728193146417445
              precision    recall  f1-score   support

           0       0.61      0.79      0.69      1523
           1       0.46      0.25      0.33      1045

    accuracy                           0.57      2568
   macro avg       0.53      0.52      0.51      2568
weighted avg       0.55      0.57      0.54      2568

[[1205  318]
 [ 779  266]]


###### Glove

In [26]:
model = Pipeline([('vectorizer',glove),('clf', SVC(random_state=42, kernel='rbf', gamma=0.5, probability=True))]) #('selector', SelectKBest(chi2, k=all)
model.fit(X_train, y_train)# fitting the model
predictions = model.predict(X_test)
print_scores() # using the predefined function to display results of the classification
#model.set_params(embedding__max_features=1000)# limiting the max features to 1000 and checking the model

Accuracy:  0.594626168224299
              precision    recall  f1-score   support

           0       0.60      0.99      0.74      1523
           1       0.55      0.02      0.04      1045

    accuracy                           0.59      2568
   macro avg       0.57      0.50      0.39      2568
weighted avg       0.58      0.59      0.46      2568

[[1506   17]
 [1024   21]]


###### CV (count vectorizer)

In [ ]:
#model = Pipeline([('vectorizer', cv),('selector', SelectKBest(chi2, k=1000)),('clf', SVC(random_state=42, kernel='linear', gamma=0.1, probability=True)),])
#model.fit(X_train, y_train)
#predictions = model.predict(X_test)
#print_scores() 
#model.set_params(vectorizer__max_features=1000)

In [27]:
model = Pipeline([('vectorizer', cv),('clf', SVC(random_state=42, kernel='linear', gamma=0.1, probability=True)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores() 
#model.set_params(vectorizer__max_features=1000)

Accuracy:  0.5502336448598131
              precision    recall  f1-score   support

           0       0.61      0.66      0.64      1523
           1       0.44      0.39      0.41      1045

    accuracy                           0.55      2568
   macro avg       0.53      0.52      0.52      2568
weighted avg       0.54      0.55      0.54      2568

[[1008  515]
 [ 640  405]]


###### w2v

In [28]:
model = Pipeline([('vectorizer', w2v),('clf', SVC(random_state=42, kernel='rbf', gamma=1, probability=True)),]) #('selector', SelectKBest(chi2, k=all)) 
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores() 
#model.set_params(vectorizer__max_features=1000)

Accuracy:  0.5973520249221184
              precision    recall  f1-score   support

           0       0.60      0.98      0.74      1523
           1       0.57      0.04      0.08      1045

    accuracy                           0.60      2568
   macro avg       0.58      0.51      0.41      2568
weighted avg       0.59      0.60      0.47      2568

[[1490   33]
 [1001   44]]


###### FastText

In [29]:
model = Pipeline([('vectorizer', fasttext),('clf', SVC(random_state=42, kernel='rbf', gamma=1, probability=True)),]) #('selector', SelectKBest(chi2, k=1000))
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores() 
#model.set_params(vectorizer__max_features=1000)

Accuracy:  0.5930685358255452
              precision    recall  f1-score   support

           0       0.59      1.00      0.74      1523
           1       0.00      0.00      0.00      1045

    accuracy                           0.59      2568
   macro avg       0.30      0.50      0.37      2568
weighted avg       0.35      0.59      0.44      2568

[[1523    0]
 [1045    0]]


###### BERT

In [30]:
#github base : https://github.com/prathameshmahankal/Fake-News-Detection-Using-BERT/blob/main/notebooks/train.ipynb 
model = SVC(random_state=42, kernel='linear', gamma=0.1, probability=True)
# Training 
model.fit(bert_word_training_features, y_train)
# Evaluation
predictions = model.predict(bert_word_test_features)
# Evaluation
predictions = model.predict(bert_word_test_features)
#y_prob_bert_words_svm = model.decision_function(bert_word_test_features)
print_scores()

Accuracy:  0.567367601246106
              precision    recall  f1-score   support

           0       0.60      0.81      0.69      1523
           1       0.44      0.22      0.29      1045

    accuracy                           0.57      2568
   macro avg       0.52      0.51      0.49      2568
weighted avg       0.53      0.57      0.53      2568

[[1228  295]
 [ 816  229]]


##### LR

In [31]:
from sklearn.linear_model import LogisticRegression

###### tf-idf

In [32]:
model = Pipeline([('vectorizer', tfidf),
                  ('clf',  LogisticRegression(random_state=42, multi_class='auto', solver='liblinear', penalty='l1')),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores() 
#model.set_params(embedding__max_features=1000)

Accuracy:  0.5786604361370716
              precision    recall  f1-score   support

           0       0.60      0.90      0.72      1523
           1       0.43      0.11      0.18      1045

    accuracy                           0.58      2568
   macro avg       0.51      0.51      0.45      2568
weighted avg       0.53      0.58      0.50      2568

[[1368  155]
 [ 927  118]]


###### Glove

In [33]:
model = Pipeline([('vectorizer', glove),
                  ('clf', LogisticRegression(random_state=42,multi_class='auto', solver='liblinear', penalty='l1'))])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores() 
#model.set_params(embedding__max_features=1000)

Accuracy:  0.5922897196261683
              precision    recall  f1-score   support

           0       0.59      0.99      0.74      1523
           1       0.44      0.01      0.01      1045

    accuracy                           0.59      2568
   macro avg       0.52      0.50      0.38      2568
weighted avg       0.53      0.59      0.45      2568

[[1514    9]
 [1038    7]]


###### CV 

In [34]:
model = Pipeline([('vectorizer', cv),('clf', LogisticRegression(random_state=42,multi_class='auto', solver='liblinear', penalty='l1')),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores() 
#model.set_params(vectorizer__max_features=1000)

Accuracy:  0.5650311526479751
              precision    recall  f1-score   support

           0       0.61      0.75      0.67      1523
           1       0.45      0.30      0.36      1045

    accuracy                           0.57      2568
   macro avg       0.53      0.52      0.51      2568
weighted avg       0.54      0.57      0.54      2568

[[1140  383]
 [ 734  311]]


###### w2v 

In [35]:
model = Pipeline([('vectorizer', w2v),('clf', LogisticRegression(random_state=42,multi_class='auto', solver='liblinear', penalty='l1')),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores() 
#model.set_params(vectorizer__max_features=1000)

Accuracy:  0.5845015576323987
              precision    recall  f1-score   support

           0       0.60      0.92      0.72      1523
           1       0.45      0.09      0.15      1045

    accuracy                           0.58      2568
   macro avg       0.52      0.51      0.44      2568
weighted avg       0.54      0.58      0.49      2568

[[1406  117]
 [ 950   95]]


###### FastText

In [36]:
model = Pipeline([('vectorizer', fasttext),('clf', LogisticRegression(random_state=42, multi_class='auto', solver='liblinear', penalty='l1'))])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores() 
#model.set_params(embedding__max_features=1000)

Accuracy:  0.5969626168224299
              precision    recall  f1-score   support

           0       0.60      0.99      0.74      1523
           1       0.65      0.02      0.04      1045

    accuracy                           0.60      2568
   macro avg       0.62      0.51      0.39      2568
weighted avg       0.62      0.60      0.46      2568

[[1511   12]
 [1023   22]]


###### BERT

In [37]:
#github base : https://github.com/prathameshmahankal/Fake-News-Detection-Using-BERT/blob/main/notebooks/train.ipynb 
model = LogisticRegression(random_state=42, multi_class='auto', solver='liblinear', penalty='l1')
# Training 
model.fit(bert_word_training_features, y_train)
# Evaluation
predictions = model.predict(bert_word_test_features)
# Evaluation
predictions = model.predict(bert_word_test_features)
#y_prob_bert_words_svm = model.decision_function(bert_word_test_features)
print_scores()

Accuracy:  0.5689252336448598
              precision    recall  f1-score   support

           0       0.60      0.79      0.69      1523
           1       0.45      0.24      0.31      1045

    accuracy                           0.57      2568
   macro avg       0.52      0.52      0.50      2568
weighted avg       0.54      0.57      0.53      2568

[[1209  314]
 [ 793  252]]


##### RF 

In [38]:
from sklearn.ensemble import RandomForestClassifier

###### tf-idf

In [39]:
model = Pipeline([
    ('vectorizer', tfidf),
    ('clf', RandomForestClassifier(random_state=42, verbose=100, n_estimators=50, n_jobs=-1)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores() # using the predefined function to display results of the classification
#model.set_params(embedding__max_features=1000)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.
building tree 1 of 50building tree 2 of 50

building tree 3 of 50[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    0.2s

building tree 4 of 50[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    0.2s

building tree 5 of 50[Parallel(n_jobs=-1)]: Done   3 tasks      | elapsed:    0.4s

building tree 6 of 50[Parallel(n_jobs=-1)]: Done   4 tasks      | elapsed:    0.4s

building tree 7 of 50[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    0.5s

building tree 8 of 50[Parallel(n_jobs=-1)]: Done   6 tasks      | elapsed:    0.5s

building tree 9 of 50[Parallel(n_jobs=-1)]: Done   7 tasks      | elapsed:    0.7s
building tree 10 of 50[Parallel(n_jobs=-1)]: Done   8 tasks      | elapsed:    0.7s


building tree 11 of 50[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:    0.9s

building tree 12 of 50[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    0.9s

building tree 13 of 50[Parallel(

###### Glove

In [40]:
model = Pipeline([
    ('vectorizer', glove),
    ('clf', RandomForestClassifier(random_state=42, verbose=100, n_estimators=50, n_jobs=-1)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.
building tree 1 of 50building tree 2 of 50

building tree 3 of 50[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    0.1s

building tree 4 of 50[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    0.1s

building tree 5 of 50[Parallel(n_jobs=-1)]: Done   3 tasks      | elapsed:    0.2s

building tree 6 of 50[Parallel(n_jobs=-1)]: Done   4 tasks      | elapsed:    0.2s

building tree 7 of 50[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    0.3s

building tree 8 of 50[Parallel(n_jobs=-1)]: Done   6 tasks      | elapsed:    0.3s

building tree 9 of 50[Parallel(n_jobs=-1)]: Done   7 tasks      | elapsed:    0.4s

building tree 10 of 50[Parallel(n_jobs=-1)]: Done   8 tasks      | elapsed:    0.4s

building tree 11 of 50[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:    0.5s

building tree 12 of 50[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    0.5s

building tree 13 of 50[Parallel(

###### cv

In [41]:
model = Pipeline([
    ('vectorizer', cv),
    ('clf', RandomForestClassifier(random_state=42, verbose=100, n_estimators=20, n_jobs=-1)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.
building tree 1 of 20
building tree 2 of 20
building tree 3 of 20[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    0.2s

building tree 4 of 20[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    0.2s

building tree 5 of 20[Parallel(n_jobs=-1)]: Done   3 tasks      | elapsed:    0.4s

building tree 6 of 20[Parallel(n_jobs=-1)]: Done   4 tasks      | elapsed:    0.4s

building tree 7 of 20[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    0.6s

building tree 8 of 20[Parallel(n_jobs=-1)]: Done   6 tasks      | elapsed:    0.6s

building tree 9 of 20[Parallel(n_jobs=-1)]: Done   7 tasks      | elapsed:    0.8s

building tree 10 of 20[Parallel(n_jobs=-1)]: Done   8 tasks      | elapsed:    0.8s

building tree 11 of 20[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:    1.0s

building tree 12 of 20[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    1.0s

building tree 13 of 20[Parallel(

###### w2v

In [42]:
model = Pipeline([
    ('vectorizer', w2v),
    ('clf', RandomForestClassifier(random_state=42, verbose=100, n_estimators=50, n_jobs=-1)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.
building tree 1 of 50building tree 2 of 50

building tree 3 of 50[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    0.2s

building tree 4 of 50[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    0.3s

building tree 5 of 50[Parallel(n_jobs=-1)]: Done   3 tasks      | elapsed:    0.5s

building tree 6 of 50[Parallel(n_jobs=-1)]: Done   4 tasks      | elapsed:    0.5s

building tree 7 of 50[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    0.8s

building tree 8 of 50[Parallel(n_jobs=-1)]: Done   6 tasks      | elapsed:    0.8s

building tree 9 of 50[Parallel(n_jobs=-1)]: Done   7 tasks      | elapsed:    1.0s

building tree 10 of 50[Parallel(n_jobs=-1)]: Done   8 tasks      | elapsed:    1.0s

building tree 11 of 50[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:    1.3s

building tree 12 of 50[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    1.3s

building tree 13 of 50[Parallel(

###### FastText

In [43]:
model = Pipeline([
    ('vectorizer', fasttext),
    ('clf', RandomForestClassifier(random_state=42, verbose=100, n_estimators=50, n_jobs=-1)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.
building tree 1 of 50
building tree 2 of 50
building tree 3 of 50[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    0.3s

building tree 4 of 50[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    0.3s

building tree 5 of 50[Parallel(n_jobs=-1)]: Done   3 tasks      | elapsed:    0.5s

building tree 6 of 50[Parallel(n_jobs=-1)]: Done   4 tasks      | elapsed:    0.6s

building tree 7 of 50[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    0.8s

building tree 8 of 50[Parallel(n_jobs=-1)]: Done   6 tasks      | elapsed:    0.8s

building tree 9 of 50[Parallel(n_jobs=-1)]: Done   7 tasks      | elapsed:    1.1s

building tree 10 of 50[Parallel(n_jobs=-1)]: Done   8 tasks      | elapsed:    1.1s

building tree 11 of 50[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:    1.4s

building tree 12 of 50[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    1.4s

building tree 13 of 50[Parallel(

###### BERT

In [44]:
#github base : https://github.com/prathameshmahankal/Fake-News-Detection-Using-BERT/blob/main/notebooks/train.ipynb 
model = RandomForestClassifier(random_state=42, verbose=100, n_estimators=50, n_jobs=-1)
# Training 
model.fit(bert_word_training_features, y_train)
# Evaluation
predictions = model.predict(bert_word_test_features)
# Evaluation
predictions = model.predict(bert_word_test_features)
#y_prob_bert_words_svm = model.decision_function(bert_word_test_features)
print_scores()

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.
building tree 1 of 50building tree 2 of 50

building tree 3 of 50[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    0.4s

building tree 4 of 50[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    0.4s

building tree 5 of 50[Parallel(n_jobs=-1)]: Done   3 tasks      | elapsed:    0.8s

building tree 6 of 50[Parallel(n_jobs=-1)]: Done   4 tasks      | elapsed:    0.8s

building tree 7 of 50[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    1.2s

building tree 8 of 50[Parallel(n_jobs=-1)]: Done   6 tasks      | elapsed:    1.3s

building tree 9 of 50[Parallel(n_jobs=-1)]: Done   7 tasks      | elapsed:    1.6s

building tree 10 of 50[Parallel(n_jobs=-1)]: Done   8 tasks      | elapsed:    1.8s

building tree 11 of 50[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:    2.0s

building tree 12 of 50[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    2.2s

building tree 13 of 50[Parallel(

##### NB 

In [45]:
from sklearn.naive_bayes import MultinomialNB, BernoulliNB

###### tf-idf

In [46]:
model = Pipeline([
    ('vectorizer', tfidf),
    ('clf', MultinomialNB(alpha=0.5, fit_prior=False)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5611370716510904
              precision    recall  f1-score   support

           0       0.62      0.69      0.65      1523
           1       0.45      0.38      0.41      1045

    accuracy                           0.56      2568
   macro avg       0.53      0.53      0.53      2568
weighted avg       0.55      0.56      0.55      2568

[[1046  477]
 [ 650  395]]


###### Glove

In [47]:
model = Pipeline([
    ('vectorizer', glove),
    ('clf', BernoulliNB(alpha=0.1, fit_prior=True)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5942367601246106
              precision    recall  f1-score   support

           0       0.60      0.93      0.73      1523
           1       0.51      0.11      0.18      1045

    accuracy                           0.59      2568
   macro avg       0.55      0.52      0.46      2568
weighted avg       0.56      0.59      0.51      2568

[[1411  112]
 [ 930  115]]


###### cv

In [48]:
model = Pipeline([
    ('vectorizer', cv),
    ('clf', MultinomialNB(alpha=1, fit_prior=False)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5607476635514018
              precision    recall  f1-score   support

           0       0.62      0.67      0.65      1523
           1       0.45      0.40      0.42      1045

    accuracy                           0.56      2568
   macro avg       0.54      0.53      0.53      2568
weighted avg       0.55      0.56      0.55      2568

[[1026  497]
 [ 631  414]]


###### w2v

In [49]:
model = Pipeline([
    ('vectorizer', w2v),
    ('clf', BernoulliNB(alpha=0.5, fit_prior=True)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5447819314641744
              precision    recall  f1-score   support

           0       0.61      0.64      0.63      1523
           1       0.44      0.40      0.42      1045

    accuracy                           0.54      2568
   macro avg       0.52      0.52      0.52      2568
weighted avg       0.54      0.54      0.54      2568

[[977 546]
 [623 422]]


###### FastText

In [50]:
model = Pipeline([
    ('vectorizer', fasttext),
    ('clf', BernoulliNB(alpha=1, fit_prior=True)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5549065420560748
              precision    recall  f1-score   support

           0       0.62      0.66      0.64      1523
           1       0.45      0.41      0.43      1045

    accuracy                           0.55      2568
   macro avg       0.53      0.53      0.53      2568
weighted avg       0.55      0.55      0.55      2568

[[1000  523]
 [ 620  425]]


###### BERT

In [51]:
#github base : https://github.com/prathameshmahankal/Fake-News-Detection-Using-BERT/blob/main/notebooks/train.ipynb 
model = BernoulliNB(alpha=0.1, fit_prior=True)
# Training 
model.fit(bert_word_training_features, y_train)
# Evaluation
predictions = model.predict(bert_word_test_features)
# Evaluation
predictions = model.predict(bert_word_test_features)
#y_prob_bert_words_svm = model.decision_function(bert_word_test_features)
print_scores()

Accuracy:  0.5490654205607477
              precision    recall  f1-score   support

           0       0.63      0.58      0.60      1523
           1       0.45      0.51      0.48      1045

    accuracy                           0.55      2568
   macro avg       0.54      0.54      0.54      2568
weighted avg       0.56      0.55      0.55      2568

[[880 643]
 [515 530]]


##### MLP 

In [52]:
from sklearn.neural_network import MLPClassifier

###### tf-idf

In [53]:
model = Pipeline([
    ('vectorizer', tfidf),
    ('clf',  MLPClassifier(random_state=42, batch_size=20, max_iter=40,
                                 activation='logistic', solver='adam')),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5323208722741433
              precision    recall  f1-score   support

           0       0.60      0.61      0.61      1523
           1       0.42      0.41      0.42      1045

    accuracy                           0.53      2568
   macro avg       0.51      0.51      0.51      2568
weighted avg       0.53      0.53      0.53      2568

[[934 589]
 [612 433]]


###### Glove 

In [54]:
model = Pipeline([
    ('vectorizer', glove),
    ('clf',  MLPClassifier(random_state=42, batch_size=20, max_iter=40, activation='relu', solver='adam')),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.57398753894081
              precision    recall  f1-score   support

           0       0.60      0.85      0.70      1523
           1       0.44      0.18      0.25      1045

    accuracy                           0.57      2568
   macro avg       0.52      0.51      0.48      2568
weighted avg       0.54      0.57      0.52      2568

[[1287  236]
 [ 858  187]]


###### cv

In [55]:
model = Pipeline([
    ('vectorizer', cv),
    ('clf',   MLPClassifier(random_state=42, batch_size=20, max_iter=40,
                                 activation='relu', solver='lbfgs')),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5463395638629284
              precision    recall  f1-score   support

           0       0.61      0.64      0.63      1523
           1       0.44      0.41      0.42      1045

    accuracy                           0.55      2568
   macro avg       0.53      0.53      0.53      2568
weighted avg       0.54      0.55      0.54      2568

[[973 550]
 [615 430]]


###### w2v

In [56]:
model = Pipeline([
    ('vectorizer', w2v),
    ('clf',  MLPClassifier(random_state=42, batch_size=20, max_iter=40,
                                 activation='relu', solver='adam')),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5529595015576324
              precision    recall  f1-score   support

           0       0.60      0.71      0.65      1523
           1       0.43      0.32      0.37      1045

    accuracy                           0.55      2568
   macro avg       0.52      0.52      0.51      2568
weighted avg       0.53      0.55      0.54      2568

[[1085  438]
 [ 710  335]]


###### FastText

In [57]:
model = Pipeline([
    ('vectorizer', fasttext),
    ('clf',  MLPClassifier(random_state=42, batch_size=20, max_iter=40, activation='relu', solver='adam')),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5545171339563862
              precision    recall  f1-score   support

           0       0.60      0.77      0.67      1523
           1       0.42      0.24      0.31      1045

    accuracy                           0.55      2568
   macro avg       0.51      0.51      0.49      2568
weighted avg       0.52      0.55      0.52      2568

[[1172  351]
 [ 793  252]]


###### BERT

In [58]:
#github base : https://github.com/prathameshmahankal/Fake-News-Detection-Using-BERT/blob/main/notebooks/train.ipynb 
model = MLPClassifier(random_state=42, batch_size=20, max_iter=40,activation='logistic', solver='adam')
# Training 
model.fit(bert_word_training_features, y_train)
# Evaluation
predictions = model.predict(bert_word_test_features)
# Evaluation
predictions = model.predict(bert_word_test_features)
#y_prob_bert_words_svm = model.decision_function(bert_word_test_features)
print_scores()

Accuracy:  0.5607476635514018
              precision    recall  f1-score   support

           0       0.63      0.63      0.63      1523
           1       0.46      0.46      0.46      1045

    accuracy                           0.56      2568
   macro avg       0.54      0.54      0.54      2568
weighted avg       0.56      0.56      0.56      2568

[[963 560]
 [568 477]]


##### EXTRA classifier

In [59]:
from sklearn.ensemble import ExtraTreesClassifier

###### tf-idf

In [60]:
model = Pipeline([
    ('vectorizer', tfidf),
    ('clf',  ExtraTreesClassifier(random_state=42, n_estimators=50, n_jobs=-1)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5751557632398754
              precision    recall  f1-score   support

           0       0.61      0.81      0.69      1523
           1       0.46      0.23      0.30      1045

    accuracy                           0.58      2568
   macro avg       0.53      0.52      0.50      2568
weighted avg       0.54      0.58      0.53      2568

[[1241  282]
 [ 809  236]]


###### Glove

In [61]:
model = Pipeline([
    ('vectorizer', glove),
    ('clf',  ExtraTreesClassifier(random_state=42, n_estimators=50, n_jobs=-1)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5864485981308412
              precision    recall  f1-score   support

           0       0.60      0.88      0.72      1523
           1       0.48      0.16      0.23      1045

    accuracy                           0.59      2568
   macro avg       0.54      0.52      0.48      2568
weighted avg       0.55      0.59      0.52      2568

[[1343  180]
 [ 882  163]]


###### cv

In [62]:
model = Pipeline([
    ('vectorizer', cv),
    ('clf',   ExtraTreesClassifier(random_state=42, n_estimators=50, n_jobs=-1)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5681464174454829
              precision    recall  f1-score   support

           0       0.61      0.78      0.68      1523
           1       0.45      0.27      0.33      1045

    accuracy                           0.57      2568
   macro avg       0.53      0.52      0.51      2568
weighted avg       0.54      0.57      0.54      2568

[[1181  342]
 [ 767  278]]


###### w2v

In [63]:
model = Pipeline([
    ('vectorizer', w2v),
    ('clf',   ExtraTreesClassifier(random_state=42, n_estimators=50, n_jobs=-1)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5903426791277259
              precision    recall  f1-score   support

           0       0.60      0.91      0.72      1523
           1       0.49      0.13      0.21      1045

    accuracy                           0.59      2568
   macro avg       0.55      0.52      0.47      2568
weighted avg       0.56      0.59      0.51      2568

[[1379  144]
 [ 908  137]]


###### FastText

In [64]:
model = Pipeline([
    ('vectorizer', fasttext),
    ('clf',  ExtraTreesClassifier(random_state=42, n_estimators=50, n_jobs=-1)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5763239875389408
              precision    recall  f1-score   support

           0       0.60      0.89      0.71      1523
           1       0.43      0.12      0.19      1045

    accuracy                           0.58      2568
   macro avg       0.51      0.50      0.45      2568
weighted avg       0.53      0.58      0.50      2568

[[1356  167]
 [ 921  124]]


###### BERT

In [65]:
#github base : https://github.com/prathameshmahankal/Fake-News-Detection-Using-BERT/blob/main/notebooks/train.ipynb 
model = ExtraTreesClassifier(random_state=42, n_estimators=50, n_jobs=-1)
model.fit(bert_word_training_features, y_train)
# Evaluation
predictions = model.predict(bert_word_test_features)
# Evaluation
predictions = model.predict(bert_word_test_features)
#y_prob_bert_words_svm = model.decision_function(bert_word_test_features)
print_scores()

Accuracy:  0.588006230529595
              precision    recall  f1-score   support

           0       0.60      0.90      0.72      1523
           1       0.48      0.13      0.20      1045

    accuracy                           0.59      2568
   macro avg       0.54      0.52      0.46      2568
weighted avg       0.55      0.59      0.51      2568

[[1377  146]
 [ 912  133]]


##### CNN

###### tf-idf

In [ ]:
model = Pipeline([
    ('vectorizer', CountVectorizer(analyzer='word',preprocessor=preprocess,tokenizer=Tokenizer,stop_words=stopwords_list)),
    ('norm2', TfidfTransformer(norm=None)),
    ('selector', SelectKBest(chi2, k=1000)),
    ('clf',  ),
])#analyzer='word', lowercase=True, use_idf=True, stop_words='english
# fitting the model
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores() # using the predefined function to display results of the classification
# limiting the max features to 1000 and checking the model
model.set_params(vectorizer__max_features=1000)

###### Glove

In [ ]:
model = Pipeline([('vectorizer', cv),('selector', SelectKBest(chi2, k=1000)),('clf', SVC(random_state=42, kernel='linear', gamma=0.1, probability=True)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores() 
model.set_params(vectorizer__max_features=1000)

###### cv

In [ ]:
model = Pipeline([('vectorizer', cv),('selector', SelectKBest(chi2, k=1000)),('clf', SVC(random_state=42, kernel='linear', gamma=0.1, probability=True)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores() 
model.set_params(vectorizer__max_features=1000)

###### w2v

In [ ]:
model = Pipeline([('vectorizer', cv),('selector', SelectKBest(chi2, k=1000)),('clf', SVC(random_state=42, kernel='linear', gamma=0.1, probability=True)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores() 
model.set_params(vectorizer__max_features=1000)

###### FastText

In [ ]:
model = Pipeline([('vectorizer', cv),('selector', SelectKBest(chi2, k=1000)),('clf', SVC(random_state=42, kernel='linear', gamma=0.1, probability=True)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores() 
model.set_params(vectorizer__max_features=1000)

###### BERT

In [ ]:
#github base : https://github.com/prathameshmahankal/Fake-News-Detection-Using-BERT/blob/main/notebooks/train.ipynb 
model = SVC(random_state=42, kernel='linear', gamma=0.1, probability=True)
# Training 
model.fit(bert_word_training_features, y_train)
# Evaluation
predictions = model.predict(bert_word_test_features)
# Evaluation
predictions = model.predict(bert_word_test_features)
#y_prob_bert_words_svm = model.decision_function(bert_word_test_features)
print_scores()

##### KNN 

In [66]:
from sklearn.neighbors import KNeighborsClassifier

###### tf-idf

In [67]:
model = Pipeline([
    ('vectorizer', tfidf),
    ('clf',  KNeighborsClassifier(n_neighbors=5, n_jobs=-1)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5471183800623053
              precision    recall  f1-score   support

           0       0.60      0.70      0.65      1523
           1       0.43      0.33      0.37      1045

    accuracy                           0.55      2568
   macro avg       0.51      0.51      0.51      2568
weighted avg       0.53      0.55      0.53      2568

[[1061  462]
 [ 701  344]]


###### Glove

In [68]:
model = Pipeline([
    ('vectorizer', glove),
    ('clf',   KNeighborsClassifier(n_neighbors=5, n_jobs=-1)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5486760124610592
              precision    recall  f1-score   support

           0       0.61      0.68      0.64      1523
           1       0.43      0.35      0.39      1045

    accuracy                           0.55      2568
   macro avg       0.52      0.52      0.52      2568
weighted avg       0.54      0.55      0.54      2568

[[1039  484]
 [ 675  370]]


###### cv

In [69]:
model = Pipeline([
    ('vectorizer', cv),
    ('clf',   KNeighborsClassifier(n_neighbors=3, n_jobs=-1)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5654205607476636
              precision    recall  f1-score   support

           0       0.60      0.81      0.69      1523
           1       0.43      0.21      0.28      1045

    accuracy                           0.57      2568
   macro avg       0.51      0.51      0.48      2568
weighted avg       0.53      0.57      0.52      2568

[[1235  288]
 [ 828  217]]


###### w2v

In [70]:
model = Pipeline([
    ('vectorizer', w2v),
    ('clf',  KNeighborsClassifier(n_neighbors=5, n_jobs=-1)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5521806853582555
              precision    recall  f1-score   support

           0       0.60      0.72      0.66      1523
           1       0.43      0.31      0.36      1045

    accuracy                           0.55      2568
   macro avg       0.52      0.51      0.51      2568
weighted avg       0.53      0.55      0.54      2568

[[1095  428]
 [ 722  323]]


###### FastText

In [71]:
model = Pipeline([
    ('vectorizer', fasttext),
    ('clf',  KNeighborsClassifier(n_neighbors=5, n_jobs=-1)),])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print_scores()

Accuracy:  0.5541277258566978
              precision    recall  f1-score   support

           0       0.61      0.71      0.65      1523
           1       0.44      0.33      0.37      1045

    accuracy                           0.55      2568
   macro avg       0.52      0.52      0.51      2568
weighted avg       0.54      0.55      0.54      2568

[[1080  443]
 [ 702  343]]


###### BERT

In [72]:
#github base : https://github.com/prathameshmahankal/Fake-News-Detection-Using-BERT/blob/main/notebooks/train.ipynb 
model = KNeighborsClassifier(n_neighbors=5, n_jobs=-1)
# Training 
model.fit(bert_word_training_features, y_train)
# Evaluation
predictions = model.predict(bert_word_test_features)
# Evaluation
predictions = model.predict(bert_word_test_features)
#y_prob_bert_words_svm = model.decision_function(bert_word_test_features)
print_scores()

Accuracy:  0.5634735202492211
              precision    recall  f1-score   support

           0       0.62      0.70      0.65      1523
           1       0.46      0.37      0.41      1045

    accuracy                           0.56      2568
   macro avg       0.54      0.53      0.53      2568
weighted avg       0.55      0.56      0.55      2568

[[1060  463]
 [ 658  387]]


#### Modelos P/ 6 classes 

In [ ]:
#data
train=pd.DataFrame(dataset['train'])
test=pd.DataFrame(dataset['test'])
val=pd.DataFrame(dataset['validation'])
print(train.shape,test.shape,val.shape)
df_raw = pd.concat([train, test, val], axis=0, sort=False)
df_raw = df_raw.sample(frac=1).reset_index()
print(train['label'].unique())
print(test['label'].unique())
print(val['label'].unique())
# specifying features and labels
X= df_raw['statement']
y=df_raw['label']
from sklearn.model_selection import train_test_split
# specifying train and test split with ratio of 80:20
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state = 0, stratify=y)
print(len(X_train), len(X_test))
print(len(y_train), len(y_test))

Modelos Bert 

In [ ]:
bert_word_training_features = X_train.apply(embeddToBERT)
bert_word_test_features = X_test.apply(embeddToBERT)
feature = [x for x in bert_word_training_features.transpose()]
bert_word_training_features = np.asarray(feature)
feature = [x for x in bert_word_test_features.transpose()]
bert_word_test_features = np.asarray(feature)
print(bert_word_training_features.shape)

In [ ]:
#github base : https://github.com/prathameshmahankal/Fake-News-Detection-Using-BERT/blob/main/notebooks/train.ipynb 
model = SVC(random_state=42, kernel='linear', gamma=0.1, probability=True)
# Training 
model.fit(bert_word_training_features, y_train)
# Evaluation
predictions = model.predict(bert_word_test_features)
# Evaluation
predictions = model.predict(bert_word_test_features)
#y_prob_bert_words_svm = model.decision_function(bert_word_test_features)
print_scores()

In [ ]:
#github base : https://github.com/prathameshmahankal/Fake-News-Detection-Using-BERT/blob/main/notebooks/train.ipynb 
model = LogisticRegression(random_state=42, multi_class='auto', solver='liblinear', penalty='l1')
# Training 
model.fit(bert_word_training_features, y_train)
# Evaluation
predictions = model.predict(bert_word_test_features)
# Evaluation
predictions = model.predict(bert_word_test_features)
#y_prob_bert_words_svm = model.decision_function(bert_word_test_features)
print_scores()

In [ ]:
#github base : https://github.com/prathameshmahankal/Fake-News-Detection-Using-BERT/blob/main/notebooks/train.ipynb 
model = RandomForestClassifier(random_state=42, verbose=100, n_estimators=50, n_jobs=-1)
# Training 
model.fit(bert_word_training_features, y_train)
# Evaluation
predictions = model.predict(bert_word_test_features)
# Evaluation
predictions = model.predict(bert_word_test_features)
#y_prob_bert_words_svm = model.decision_function(bert_word_test_features)
print_scores()

In [ ]:
ithub base : https://github.com/prathameshmahankal/Fake-News-Detection-Using-BERT/blob/main/notebooks/train.ipynb 
model = BernoulliNB(alpha=0.1, fit_prior=True)
# Training 
model.fit(bert_word_training_features, y_train)
# Evaluation
predictions = model.predict(bert_word_test_features)
# Evaluation
predictions = model.predict(bert_word_test_features)
#y_prob_bert_words_svm = model.decision_function(bert_word_test_features)
print_scores()

In [ ]:
#github base : https://github.com/prathameshmahankal/Fake-News-Detection-Using-BERT/blob/main/notebooks/train.ipynb 
model = MLPClassifier(random_state=42, batch_size=20, max_iter=40,activation='logistic', solver='adam')
# Training 
model.fit(bert_word_training_features, y_train)
# Evaluation
predictions = model.predict(bert_word_test_features)
# Evaluation
predictions = model.predict(bert_word_test_features)
#y_prob_bert_words_svm = model.decision_function(bert_word_test_features)
print_scores()

In [ ]:
#github base : https://github.com/prathameshmahankal/Fake-News-Detection-Using-BERT/blob/main/notebooks/train.ipynb 
model = ExtraTreesClassifier(random_state=42, n_estimators=50, n_jobs=-1)
model.fit(bert_word_training_features, y_train)
# Evaluation
predictions = model.predict(bert_word_test_features)
# Evaluation
predictions = model.predict(bert_word_test_features)
#y_prob_bert_words_svm = model.decision_function(bert_word_test_features)
print_scores()

In [ ]:
#github base : https://github.com/prathameshmahankal/Fake-News-Detection-Using-BERT/blob/main/notebooks/train.ipynb 
model = KNeighborsClassifier(n_neighbors=5, n_jobs=-1)
# Training 
model.fit(bert_word_training_features, y_train)
# Evaluation
predictions = model.predict(bert_word_test_features)
# Evaluation
predictions = model.predict(bert_word_test_features)
#y_prob_bert_words_svm = model.decision_function(bert_word_test_features)
print_scores()

### *EXTRAS*

### Diversity Analysis 

In [ ]:
!pip install deslib

     |████████████████████████████████| 158 kB 5.6 MB/s 


In [ ]:
!pip install umap
!pip install umap-learn

  Created wheel for umap: filename=umap-0.1.1-py3-none-any.whl size=3564 sha256=9995b5cd89e760dcf096249f0930c87c1069b25211e6f607b4b47c0015d03721
  Stored in directory: /root/.cache/pip/wheels/65/55/85/945cfb3d67373767e4dc3e9629300a926edde52633df4f0efe
Successfully built umap
     |████████████████████████████████| 86 kB 876 kB/s 
     |████████████████████████████████| 1.1 MB 8.5 MB/s 
  Created wheel for umap-learn: filename=umap_learn-0.5.2-py3-none-any.whl size=82709 sha256=5b14426ff4ceb3f18f7654554b3b06a63f4e101863129305106d57d2207e5dc4
  Stored in directory: /root/.cache/pip/wheels/84/1b/c6/aaf68a748122632967cef4dffef68224eb16798b6793257d82
  Created wheel for pynndescent: filename=pynndescent-0.5.5-py3-none-any.whl size=52603 sha256=02f9123c3b4378668a0f5d9febf135e8d307c2512cc788a880bc0eb8635a9f8e
  Stored in directory: /root/.cache/pip/wheels/af/e9/33/04db1436df0757c42fda8ea6796d7a8586e23c85fac355f476
Successfully built umap-learn pynndescent


In [ ]:
import pandas as pd
import numpy as np
from sklearn.manifold import MDS, TSNE
from deslib.util.diversity import double_fault
import matplotlib.lines as mlines
#from umap import UMAP

In [ ]:
!pip install 'umap-learn==0.3.10'

     |████████████████████████████████| 40 kB 3.6 MB/s 
  Created wheel for umap-learn: filename=umap_learn-0.3.10-py3-none-any.whl size=38883 sha256=8ba8b52ff417dffb860253b4c04b008a02db4d91751f0c4f908096e52f5cc2e3
  Stored in directory: /root/.cache/pip/wheels/ea/d0/8f/9e64bfc5ed0645f89b639196bef92daf5c704285133efce12f
Successfully built umap-learn
  Attempting uninstall: umap-learn
    Found existing installation: umap-learn 0.5.2
    Uninstalling umap-learn-0.5.2:
      Successfully uninstalled umap-learn-0.5.2


In [ ]:
import umap.umap_ as umap

In [ ]:
from umap.umap_ import UMAP

In [ ]:
def compute_pairwise_diversity_matrix(targets, prediction_matrix, diversity_func):
    n_classifiers = prediction_matrix.shape[1]
    diversity = np.zeros((n_classifiers, n_classifiers))
    for clf_index in range(n_classifiers):
        for clf_index2 in range(clf_index + 1, n_classifiers):
            this_diversity = diversity_func(targets,
                                            prediction_matrix[:, clf_index],
                                            prediction_matrix[:, clf_index2])

            diversity[clf_index, clf_index2] = this_diversity
            diversity[clf_index2, clf_index] = this_diversity

    return diversity

In [ ]:
def compute_matrix_embedding(dataset, n_classifiers, n_features, method='mds', n_neighbors=5, min_dist=0.7
):
    D = compute_pairwise_diversity_matrix(y.to_numpy(), X.to_numpy(), double_fault)
    D = 1/D
    D[D==np.inf] = 0
    if method == 'mds':
        method = MDS(dissimilarity='precomputed', random_state=123456987, n_init=20, max_iter=100000)
    elif method == 'tsne':
        method = TSNE(perplexity=25, init='pca', random_state=42, early_exaggeration=50, 
                      learning_rate=200, n_iter=2500, angle=0.5)
    else:        
        method = UMAP(n_neighbors=2, metric='euclidean', random_state=123456987, min_dist=0.7, n_components=2,)
    D_tilde = method.fit_transform(D)
    D_tilde = D_tilde.reshape(n_classifiers, n_features, 2)
    return D_tilde

In [ ]:
from matplotlib import pyplot as plt
def plot_diversity(D_changed, method_tmp, dataset, title):
    s = 100
    colors = {}
    colors[0] = '#DAA520'
    colors[1] = '#FF0000'
    colors[2] = '#0000FF'
    colors[3] = '#228B22'
    colors[4] = '#000000'
    markers = {}
    markers[0] = 'X'
    markers[1] = 'd'
    markers[2] = '*'
    markers[3] = "^"
    markers[4] = 'o'
    n_classifiers, n_features, _ = D_changed.shape
    plt.figure(figsize=(15,10))
    method=0
    for idx in range(n_classifiers):
        for idx2 in range(n_features):
            x, y = D_changed[idx,idx2, 0], D_changed[idx,idx2, 1]
            plt.scatter(x, y, color=colors[idx2], s=s, lw=0, marker=markers[idx2])
            plt.annotate(method_tmp[method], xy=(x, y), textcoords='offset points', xytext=(5, 15), ha='right', va='top')  
            method += 1
    
    m1 = mlines.Line2D([], [], color=colors[0], marker=markers[0], linestyle='None', markersize=10, label='CV')
    m2 = mlines.Line2D([], [], color=colors[1], marker=markers[1], linestyle='None', markersize=10, label='TFIDF')
    m3 = mlines.Line2D([], [], color=colors[2], marker=markers[2], linestyle='None', markersize=10, label='Glove')
    m4 = mlines.Line2D([], [], color=colors[3], marker=markers[3], linestyle='None', markersize=10, label='Word2Vec')
    m5 = mlines.Line2D([], [], color=colors[4], marker=markers[4], linestyle='None', markersize=10, label='FastText')
    plt.title('CPS ' + dataset+' dataset')
    plt.legend(handles=[m1, m2, m3, m4, m5])
    plt.tight_layout()
    plt.savefig(title + "_" + dataset_name.upper()+'_dataset.pdf', dpi=450)

In [ ]:
predictions

array([4, 2, 2, ..., 5, 3, 1])

In [ ]:
n_classifiers = 1
method = 'umap'
n_features = 1
#label, methods = load_predictions(dataset)
#methods_name = [name.split('-', 1)[0] for name in methods.columns]
D_tilde = compute_matrix_embedding(dataset, n_classifiers, n_features, method)
plot_diversity(D_tilde, methods_name, dataset_name, method)

IndexError: ignored

### Pre processing 

#### Converting Multiclass into two classes

In [ ]:
#function for mapping labels "true, mostly-true, half-true" to TRUE and "false, barely-true, pants-fire" to FAKE.
def binary_class_dataset(data):
    
    data = data.iloc[:, [2, 3]]
    data.columns = ['label', 'statement']
    Original_labels = {'true': 'True','mostly-true': 'True','half-true': 'True',
        'false': 'Fake','barely-true': 'Fake','pants-fire': 'Fake'}
    data['label'] = data['label'].map(Original_labels)
    return data